apiVersion: v1
kind: ConfigMap
metadata:
  name: beehive-nodes-service
data:
  NODE_STATE_API: https://<beekeeper>/api/state
  RMQ_URL: http://host.docker.internal:15672
  RMQ_USERNAME: beehive-master
  RMQ_PASSWORD: beehive-master
---
apiVersion: v1
kind: Service
metadata:
  name: beehive-nodes-service
spec:
  selector:
    app: beehive-nodes-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beehive-nodes-service
spec:
  selector:
    matchLabels:
      app: beehive-nodes-service
  template:
    metadata:
      labels:
        app: beehive-nodes-service
    spec:
      containers:
      - name: beehive-nodes-service
        image: waggle/beehive-nodes-service
        envFrom:
        - configMapRef:
            name: beehive-nodes-service
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command: ["/bin/sh", "-ec", "beehive-nodes-service -q ping"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10



